-- ========================================================
-- ANEMONE CLIMBING HOLDS - SUPABASE DATABASE SCHEMA
-- Compatible with existing Supabase projects!
-- ========================================================

-- 1. Create ANEMONE_PRODUCTS Table
CREATE TABLE IF NOT EXISTS public.anemone_products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  slug TEXT UNIQUE NOT NULL,
  category TEXT NOT NULL DEFAULT 'Holds',
  material TEXT NOT NULL DEFAULT 'PU',
  price NUMERIC NOT NULL DEFAULT 0,
  stock INT NOT NULL DEFAULT 20,
  description TEXT,
  short_description TEXT,
  image TEXT,
  images JSONB DEFAULT '[]'::jsonb,
  variants JSONB DEFAULT '[]'::jsonb,
  is_new BOOLEAN DEFAULT true,
  is_featured BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Create ANEMONE_ORDERS Table
CREATE TABLE IF NOT EXISTS public.anemone_orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_no TEXT NOT NULL,
  customer JSONB DEFAULT '{}'::jsonb,
  items JSONB DEFAULT '[]'::jsonb,
  subtotal NUMERIC DEFAULT 0,
  shipping_cost TEXT DEFAULT 'Diinfokan via WhatsApp',
  total NUMERIC DEFAULT 0,
  status TEXT DEFAULT 'Processing',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Enable RLS & Grant Public Access
ALTER TABLE public.anemone_products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.anemone_orders ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public read anemone_products" ON public.anemone_products;
CREATE POLICY "Allow public read anemone_products" ON public.anemone_products FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow public insert anemone_products" ON public.anemone_products;
CREATE POLICY "Allow public insert anemone_products" ON public.anemone_products FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public update anemone_products" ON public.anemone_products;
CREATE POLICY "Allow public update anemone_products" ON public.anemone_products FOR UPDATE USING (true);

DROP POLICY IF EXISTS "Allow public delete anemone_products" ON public.anemone_products;
CREATE POLICY "Allow public delete anemone_products" ON public.anemone_products FOR DELETE USING (true);

DROP POLICY IF EXISTS "Allow public read anemone_orders" ON public.anemone_orders;
CREATE POLICY "Allow public read anemone_orders" ON public.anemone_orders FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow public insert anemone_orders" ON public.anemone_orders;
CREATE POLICY "Allow public insert anemone_orders" ON public.anemone_orders FOR INSERT WITH CHECK (true);
